project_id = "qepfrrwoqjvyicnptyam"

[functions.climate-scenario]
verify_jwt = false

[functions.fetch-climate-data]
verify_jwt = false

[functions.climate-trace]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false
