project_id = "yionqmoqsdlqsikghfzm"

[functions.climate-analysis]
verify_jwt = false

[functions.climate-chat]
verify_jwt = false

[functions.climate-realdata]
verify_jwt = false

[functions.gemini-proxy]
verify_jwt = false

[functions.generate-alerts]
verify_jwt = false

[functions.stakeholder-analysis]
verify_jwt = false

[functions.weather-data]
verify_jwt = false
